server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/image?serverTimezone=Asia/Seoul
    username: root
    password: root

  mvc:
    throw-exception-if-no-handler-found: true
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      add-mappings: false

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

# multipart 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  profiles:
    include: oauth

# 파일 경로 설정
profileImg:
  path: C:/Users/명수/Documents/공부/스프링/image/profile_imgs/

tagImg:
  path: C:/Users/명수/Documents/공부/스프링/image/tag_imgs/

feedImg:
  path: C:/Users/명수/Documents/공부/스프링/image/feed_imgs/

infoImg:
  path: C:/Users/명수/Documents/공부/스프링/image/info_imgs/
